/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: chris munoz (https://sketchfab.com/chrismunoz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/cd14b790cb4b47daa9d54422799ca95a
title: Tomons Desk Lamp
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export default function DeskLamp(props) {
  const scene = useThree((s) => s.scene);
  const group = useRef();
  const light = useRef();
  const lightTarget = useRef();
  // useHelper(light, SpotLightHelper, "cyan");
  useEffect(() => {
    scene.add(light.current.target);
    scene.add(lightTarget.current);
    light.current.target = lightTarget.current;
  }, [scene, light]);

  const { nodes, materials } = useGLTF(
    "assets/models/desk_lamp_low_poly/scene.gltf"
  );
  return (
    <>
      <group ref={group} {...props} dispose={null} scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder001_lamp_base_0.geometry}
                material={nodes.Cylinder001_lamp_base_0.material}
              />
            </group>
            <group position={[0, -0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder002_lamp_base_0.geometry}
                material={nodes.Cylinder002_lamp_base_0.material}
              />
            </group>
            <group position={[0, 1.8, -1.58]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder003_lamp_base_0.geometry}
                material={nodes.Cylinder003_lamp_base_0.material}
              />
            </group>
            <group
              position={[-0.52, 20.16, -8.21]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane009_lamp_base_0.geometry}
                material={nodes.Plane009_lamp_base_0.material}
              />
            </group>
            <group position={[0, 19.59, -6.87]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box009_lamp_base_0.geometry}
                material={nodes.Box009_lamp_base_0.material}
              />
            </group>
            <group
              position={[-0.54, 36.06, 3.54]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder018_lamp_base_0.geometry}
                material={nodes.Cylinder018_lamp_base_0.material}
              />
            </group>
            <group position={[0, 36.24, 4.45]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes["02LP_lamp_base_0"].geometry}
                material={nodes["02LP_lamp_base_0"].material}
              />
            </group>
            <group
              position={[0.02, 27.13, -1.99]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder037_lamp_base_0.geometry}
                material={nodes.Cylinder037_lamp_base_0.material}
              />
            </group>
            <group
              position={[1.67, 36.25, 4.44]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder044_lamp_base_0.geometry}
                material={nodes.Cylinder044_lamp_base_0.material}
              />
            </group>
            <group position={[0, 3.61, -1.92]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box055_lamp_base_0.geometry}
                material={nodes.Box055_lamp_base_0.material}
              />
            </group>
            <group position={[0, 21.36, -7.63]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.LP01_lamp_base_0.geometry}
                material={nodes.LP01_lamp_base_0.material}
              />
            </group>
            <group position={[0, 36.31, 1.6]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box024_lamp_base_0.geometry}
                material={nodes.Box024_lamp_base_0.material}
              />
            </group>
            <group position={[0, 2.58, -0.08]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box060_lamp_base_0.geometry}
                material={nodes.Box060_lamp_base_0.material}
              />
            </group>
            <group
              position={[0.02, 36.85, 6.94]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes["03LP_lamp_base_0"].geometry}
                material={nodes["03LP_lamp_base_0"].material}
              />
            </group>
            <group
              position={[0.03, 38.12, 5.93]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder056_lamp_base_0.geometry}
                material={nodes.Cylinder056_lamp_base_0.material}
              />
            </group>
            <group position={[0, 35.66, 11.45]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Helix007_lamp_0.geometry}
                material={materials.lamp}
              />
            </group>
            <group
              position={[0.01, 39.5, 8.73]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder060_lamp_base_0.geometry}
                material={nodes.Cylinder060_lamp_base_0.material}
              />
            </group>
            <group position={[0, 36.47, 10.92]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder061_lamp_base_0.geometry}
                material={nodes.Cylinder061_lamp_base_0.material}
              />
            </group>
            <group position={[0, 42.75, 6.45]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder059_lamp_base_0.geometry}
                material={nodes.Cylinder059_lamp_base_0.material}
              />
            </group>
            <group
              position={[0.58, 36.06, 3.54]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder071_lamp_base_0.geometry}
                material={nodes.Cylinder071_lamp_base_0.material}
              />
            </group>
            <group
              position={[0.52, 20.16, -8.21]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane013_lamp_base_0.geometry}
                material={nodes.Plane013_lamp_base_0.material}
              />
            </group>
            <group
              position={[-0.73, 5.46, -0.23]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder070_base_0.geometry}
                material={nodes.Cylinder070_base_0.material}
              />
            </group>
            <group
              position={[-1, 21.59, -7.39]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder069_base_0.geometry}
                material={nodes.Cylinder069_base_0.material}
              />
            </group>
            <group
              position={[-0.98, 26.94, -2.29]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane011_base_0.geometry}
                material={nodes.Plane011_base_0.material}
              />
            </group>
            <group
              position={[-0.97, 21.59, -7.43]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane012_base_0.geometry}
                material={nodes.Plane012_base_0.material}
              />
            </group>
            <group
              position={[-0.71, 10.79, -3.71]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane014_base_0.geometry}
                material={nodes.Plane014_base_0.material}
              />
            </group>
            <group
              position={[-0.72, 5.46, -0.25]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane015_base_0.geometry}
                material={nodes.Plane015_base_0.material}
              />
            </group>
            <group
              position={[-0.72, 10.9, -3.9]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Line004_plastik_0.geometry}
                material={nodes.Line004_plastik_0.material}
              />
            </group>
            <group
              position={[-0.88, 27.07, -2.07]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Line009_plastik_0.geometry}
                material={nodes.Line009_plastik_0.material}
              />
            </group>
            <group position={[-6.59, 0, -9.69]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Line012_plastik_0.geometry}
                material={nodes.Line012_plastik_0.material}
              />
            </group>
            <group position={[0, 21.03, -9.39]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Line013_plastik_0.geometry}
                material={nodes.Line013_plastik_0.material}
              />
            </group>
            <group position={[0, 37.74, 3.54]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Line014_plastik_0.geometry}
                material={nodes.Line014_plastik_0.material}
              />
            </group>
            <group
              position={[0.02, 21.36, -7.63]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder072_lamp_base_0.geometry}
                material={nodes.Cylinder072_lamp_base_0.material}
              />
            </group>
            <group
              position={[0.02, 10.98, -3.98]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder073_lamp_base_0.geometry}
                material={nodes.Cylinder073_lamp_base_0.material}
              />
            </group>
            <group position={[0, 22.21, -7.49]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box061_lamp_base_0.geometry}
                material={nodes.Box061_lamp_base_0.material}
              />
            </group>
            <group position={[0, 18.64, -9.27]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box062_lamp_base_0.geometry}
                material={nodes.Box062_lamp_base_0.material}
              />
            </group>
            <group position={[0, 4.12, -2.5]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Box063_lamp_base_0.geometry}
                material={nodes.Box063_lamp_base_0.material}
              />
            </group>
            <group
              position={[1.59, 19.55, -6.89]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder074_lamp_base_0.geometry}
                material={nodes.Cylinder074_lamp_base_0.material}
              />
            </group>
            <group position={[-0.97, 37, 7.09]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Cylinder075_plastik_0.geometry}
                material={nodes.Cylinder075_plastik_0.material}
              />
            </group>
            <group
              position={[1.16, 36.96, 7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder076_plastik_0.geometry}
                material={nodes.Cylinder076_plastik_0.material}
              />
            </group>
            <group
              position={[1.03, 21.59, -7.39]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder077_base_0.geometry}
                material={nodes.Cylinder077_base_0.material}
              />
            </group>
            <group
              position={[0.91, 27.07, -2.07]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Line015_plastik_0.geometry}
                material={nodes.Line015_plastik_0.material}
              />
            </group>
            <group position={[1, 26.94, -2.29]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Plane016_base_0.geometry}
                material={nodes.Plane016_base_0.material}
              />
            </group>
            <group position={[1, 21.59, -7.43]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.Plane017_base_0.geometry}
                material={nodes.Plane017_base_0.material}
              />
            </group>
            <group
              position={[0.75, 10.9, -3.9]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Line016_plastik_0.geometry}
                material={nodes.Line016_plastik_0.material}
              />
            </group>
            <group
              position={[0.02, 3.46, -0.97]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.LP01_lowpart_lamp_base_0.geometry}
                material={nodes.LP01_lowpart_lamp_base_0.material}
              />
            </group>
            <group
              position={[0.02, 41.44, 7.36]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.LP_01_base_0.geometry}
                material={nodes.LP_01_base_0.material}
              />
            </group>
            <group
              position={[0.75, 5.46, -0.23]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Cylinder079_base_0.geometry}
                material={nodes.Cylinder079_base_0.material}
              />
            </group>
            <group
              position={[0.76, 10.79, -3.71]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane020_base_0.geometry}
                material={nodes.Plane020_base_0.material}
              />
            </group>
            <group
              position={[0.75, 5.46, -0.25]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane021_base_0.geometry}
                material={nodes.Plane021_base_0.material}
              />
            </group>
          </group>
        </group>

        <spotLight
          ref={light}
          color={0xffffff}
          intensity={1}
          power={10}
          decay={2}
          penumbra={1}
          position={[0, 33, 12]}
          rotation-y={-Math.PI / 2}
          castShadow
        >
          <object3D ref={lightTarget} position={[-1.7, -2, -0.85]} />
        </spotLight>

        {/* <spotLight
          color={0xffffff}
          intensity={1}
          power={10}
          decay={2}
          penumbra={1}
          position={[2.45, 4.65, 0.7]}
          target={{ position: [-0.5, 0, -0.75] }}
        /> */}
      </group>
    </>
  );
}

useGLTF.preload("assets/models/desk_lamp_low_poly/scene.gltf");

// import React, { useRef } from "react";
// import { useGLTF, useTexture } from "@react-three/drei";
// import * as THREE from "three";

// export default function DeskLamp(props) {
//   const group = useRef();
//   const { nodes, materials } = useGLTF(
//     "assets/models/tomons_desk_lamp/scene.gltf"
//   );
//   //   const [texture, metalic] = useTexture([
//   //     "assets/models/tomons_desk_lamp/textures/Material_baseColor.jpeg",
//   //     "assets/models/tomons_desk_lamp/textures/Material_metallicRoughness.png",
//   //   ]);
//   //   texture.flipY = false;
//   //   texture.encoding = THREE.sRGBEncoding;
//   console.log(nodes, materials);

//   return (
//     <>
//       <group ref={group} {...props} dispose={null} scale={0.05}>
//         <group rotation={[-Math.PI / 2, 0, 0]}>
//           <group position={[2.23, 0, 0]} scale={[8, 12.21, 8]}>
//             <mesh
//               geometry={nodes.Backdrop_0.geometry}
//               material={materials.Material}
//             />
//           </group>
//           <group
//             position={[-0.78, 4.55, 18.05]}
//             rotation={[-Math.PI, -0.8, -Math.PI]}
//             scale={[-4.65, 0.68, 0.05]}
//           >
//             <mesh
//               geometry={nodes.LightPanels_0.geometry}
//               material={materials.Light_Panels}
//             />
//           </group>
//           <primitive object={nodes.Armature_rootJoint} />
//         </group>
//       </group>
//       <spotLight
//         color={0xffffff}
//         intensity={1}
//         power={10}
//         decay={2}
//         penumbra={1}
//         position={[2.45, 4.65, 0.7]}
//         target={{ position: [-0.5, 0, -0.75] }}
//       />
//     </>
//   );
// }

// useGLTF.preload("assets/models/tomons_desk_lamp/scene.gltf");
