/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DanielTheGamer 123 (https://sketchfab.com/DanielTheGamer123)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/camera-51a758608b17430b8e0bff83bff377c4
title: Camera
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Popcorn(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/models/pop_corn/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} scale={0.02}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.cup_blinn3_0.geometry}
            material={materials.blinn3}
          />
          <group position={[0, -0.35, 0]} scale={1.09}>
            <mesh
              geometry={nodes.corn1_lambert2_0.geometry}
              material={materials.lambert2}
            />
            <mesh
              geometry={nodes.corn1_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/pop_corn/scene.gltf");
