/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DanielTheGamer 123 (https://sketchfab.com/DanielTheGamer123)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/camera-51a758608b17430b8e0bff83bff377c4
title: Camera
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Camera(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/models/camera/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} scale={0.008}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-907.13, 0, -385.04]}>
            <mesh
              geometry={nodes.Boole_2_Mat1_0.geometry}
              material={materials["Mat.1"]}
            />
            <mesh
              geometry={nodes.Boole_2_Mat_0.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/camera/scene.gltf");
